<a href="https://colab.research.google.com/github/Suchi0506/LogRAssignment_Quiz/blob/main/LogRAssignmentQuiz_intellipat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import files
uploaded= files.upload()

Saving census-income .csv to census-income .csv

In [ ]:
df= pd.read_csv('census-income .csv')

In [ ]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual_income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
#Replacing "?" with NaN in 'occupation'
df['occupation']= df['occupation'].replace('?', np.nan)

# counting number of occupations
count= df['occupation'].nunique()
print(count)

14

In [ ]:
# Counting the people working as tech support and have an annual income greater than 50k
count = df[(df['occupation'] == 'Tech-support') & (df['annual_income'] == '>50K')]

# Getting the number of such people
print(f"Number of people working as Tech-support with an income >50K: {len(count)}")

Number of people working as Tech-support with an income >50K: 283

In [ ]:
# Total number of missing values
df.replace('?', np.nan, inplace=True)

# Counting total missing values in the dataset
total_missing_values = df.isnull().sum().sum()

total_missing_values

4262

In [ ]:
# counting number of people that are having private work classes and are not from the United States of America?
count= df[(df['workclass'] == 'Private') & ~ (df['native-country'] == 'United-States')]
len(count)

2561

In [ ]:
# counting no. of people either having Annual Income less than or equal to 50k or their working hours is greater than or equal to 40 hrs:
count = df[(df['annual_income'] == '<=50K') | (df['hours-per-week'] >= 40)]

print(f"Total count: {len(count)}")

Total count: 31823

In [ ]:
#Renaming the last column as Annual Income
df.rename(columns={'annual_income': 'Annual Income'}, inplace=True)

In [ ]:
#Removing the missing values from the dataset
df.dropna(inplace=True)

df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
Annual Income     0
dtype: int64

In [ ]:
#Changing the labels of categorical data into numerical data using Label Encoder.
from sklearn.preprocessing import LabelEncoder
label_encoder= LabelEncoder()

# Label Encoding for binary columns
df['sex'] = label_encoder.fit_transform(df['sex'])
df['Annual Income'] = label_encoder.fit_transform(df['Annual Income'])

df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Annual Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,1,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,1,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,1,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,1,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,0,0,0,40,Cuba,0

In [ ]:
#Splitting the dataset into a train and test of proportions 70:30 and set the random state to 0.
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X= df.drop('Annual Income', axis=1)
y= df['Annual Income']

In [ ]:
# Applying One-Hot Encoding for multi-category columns like 'workclass', 'occupation', etc.
X = pd.get_dummies(X, drop_first=True)

# Splitting the dataset into training and testing sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

logreg = LogisticRegression

logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

# Evaluating the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of the Logistic Regression model: {accuracy * 100:.2f}%")

Accuracy of the Logistic Regression model: 83.81%

In [ ]:
#Specificity of the model
from sklearn.metrics import confusion_matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
specificity = tn / (tn + fp)
print(f"Specificity of the model: {specificity * 100:.2f}%")

Specificity of the model: 92.50%

In [ ]:
# model’s precision when the target is False
from sklearn.metrics import precision_score
# Precision for the False class (negative class)
precision_false_class = tn / (tn + fn)
print(f"Precision (False class) of the model: {precision_false_class * 100:.2f}%")

Precision (False class) of the model: 86.72%

In [ ]:
# Total support value from the above model

total_support = (tp + fn) + (tn + fp)
print(f"Total support: {total_support}")

Total support: 9049

In [ ]:
# f1 score of the above model when the target is True
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred)
print(f"F1 score of the model: {f1 * 100:.2f}%")

F1 score of the model: 64.43%

In [ ]:
# Correctly classified records
correctly_classified = tp + tn
print(f"Correctly classified records: {correctly_classified}")

Correctly classified records: 7584